---
title: "TidyTuesday - Analyzin tour de France data in R"
author: "Notes from D.Robinsons live coding"
date: "6/2/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
theme_set(theme_classic())
```

## Analyzing Tour de France data in R

```{r}

#tdf_winners <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-07/tdf_winners.csv')

tuesdata <- tidytuesdayR::tt_load(2020, week = 15)


tuesdata <- tidytuesdayR::tt_load('2020-04-07')
tuesdata <- tidytuesdayR::tt_load(2020, week = 15)


tdf_winners <- tuesdata$tdf_winners %>% 
  mutate( year = lubridate::year(start_date), speed = distance/time_overall)


```

### First some categorical var
```{r}
tdf_winners %>%
  count( birth_country, sort = T) %>% 
  mutate( birth_country = fct_reorder(birth_country, n)) %>% 
  ggplot( aes( n,  birth_country)) +
  geom_col() +
  labs( title = "What countries were the most Tour de France winner frome?")
  
# names
tdf_winners %>% count(winner_name, sort = T)

# age 
by_decade <-  
  tdf_winners %>% 
  group_by( decade = 10 * (year %/% 10)) %>% 
  filter(decade >= 1910) %>% 
  summarise( winner_age = mean(age),
             winner_hight = mean(height, na.rm = T),
             winner_weigth = mean(weight, na.rm =T),
             winner_margin = mean(time_margin, na.rm = T),
             winner_speed = mean(speed, na.rm =T),
             ) 

by_decade %>% 
  ggplot( aes( x = decade, winner_margin*60)) +
  geom_line() +
  expand_limits( y = 0) +
  labs( y = "Winner margina", x = "Decade", title = "Tour de F races are getting closer")


by_decade %>% 
  ggplot( aes( x = decade, winner_speed)) +
  geom_line() +
  expand_limits( y = 0) +
  labs( y = "Average speed of winner (km/h)", x = "Decade", title = "Tour de F races are getting faster")

```


### Life expectency

  
```{r}
library(survival)
# Right cented data


surv_model <- tdf_winners %>% 
  distinct(winner_name, .keep_all = T) %>%
  transmute( winner_name, 
             birth_year = lubridate::year(born),
             death_year = lubridate::year(died), 
             dead = as.integer( !is.na(death_year) ) ) %>% 
  # Give those who is not death value 2020 if not death
  mutate( age_at_death_year = coalesce(death_year, 2020) - birth_year) %>% 
  survfit(Surv(age_at_death_year, dead) ~1, data = .) 

library(broom)  
glance(surv_model)

surv_model %>% plot()

```

Median life expect. is about 77.

### stage data

```{r}
stages <-  tuesdata$stage_data
tdf_stages <- tuesdata$tdf_stages %>% janitor::clean_names()

stages %>% extract(stage_results_id, "stage", "(\\d+)", convert = T) %>% distinct(stage)

# left_join
stagges_joined <- stages %>% 
  extract( stage_results_id, "stage", "stage-(.*)") %>%
  inner_join( tdf_stages %>% mutate(year = year(date)), by = c("year", "stage") ) %>% 
  mutate( rank = as.integer(rank)) %>% 
  group_by( year, stage) %>%
  mutate( finishers = sum(!is.na(rank))) %>% 
  ungroup() %>% 
  mutate( percentile_rank = 1- rank/finishers)
  
stagges_joined

stagges_joined %>% 
  group_by(winner_country) %>% 
  summarise( stages = n(), median_percentile = median(percentile_rank, na.rm = T)) %>% 
  arrange( desc(stages))


```





