---
title: "TidyTemplate"
date: 2020-09-04
output: html_output
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
theme_set(theme_light())
library(scales)

```

# Load the weekly Data

Dowload the weekly data and make available in the `tt` object.

```{r Load}

tt <- tt_load("2020-09-01")

```


# Readme

Take a look at the readme for the weekly data to get insight on the dataset.
This includes a data dictionary, source, and a link to an article on the data.

```{r Readme, eval = interactive()}

tt
## Wide data
tt$key_crop_yields

yields$wheat_tonnes_per_hectare
yields <- tt$key_crop_yields %>% janitor::clean_names() %>% rename_all( str_remove, "_tonnes.*" )

arable_land <- tt$arable_land_pin %>% janitor::clean_names() %>% 
  rename( areable_land_needed = 4)


arable_land %>% filter( entity == "Afghanistan") %>% ggplot( aes( year, areable_land_needed)) + geom_line()


fertilizer <- tt$cereal_crop_yield_vs_fertilizer_application %>% janitor::clean_names() %>% rename( yield = 4, fertilizer_use = 5)

```


```{r}
yields_tidy <- yields %>% 
  pivot_longer( wheat:bananas, names_to = "crop", values_to = "yield") %>% 
  filter(! is.na(yield))

# How much can you produce per. hectare
# same scale? consier
# Densending
yields_tidy %>% mutate( crop = fct_reorder( crop, -yield))  %>% filter( code == "USA") %>% ggplot( aes(x = year, yield)) + geom_line() + facet_wrap(~crop)
yields_tidy %>% mutate( crop = fct_reorder( crop, -yield))  %>% filter( code == "USA") %>% ggplot( aes(x = year, yield, color = crop)) + geom_line() +
  labs( x = "Year", y = "Yield (tonnes per hectare", title = "Crop yields in the USA over time")



```














# Save Image

Save your image for sharing. Be sure to use the `#TidyTuesday` hashtag in your post on twitter! 

```{r}

# This will save your most recent plot
ggsave(
  filename = "My TidyTuesday Plot.png",
  device = "png")

```
